user: pablo
home: /home/pablo
home_folders:
    - virtualenvs
    - projects
python_packages:
    - vim-bridge
    - pep8
    - pylint
    - ipython
    - virtualenvwrapper
ruby_gems:
    - tmuxinator
node_packages:
    - jshint
    - grunt-cli
    - bower
