group: pablo
distro_packages:
    - python-pip
    - ruby
    - rubygems
    - xclip
    - libpqxx
    - libevent
    - vim-enhanced
    - tmux
    - nodejs
    - npm
    - python-devel
    - python-postgresql
