group: users
scripts:
    - install_vim
distro_packages:
    - base-devel
    - git
    - nodejs
    - python-pip
    - ruby
    - openssh
    - nfs-utils
    - libevent
    - mercurial
    - curl
    - tmux
user_packages:
    heroku-toolbelt: ''
    google-chrome: ''
