group: users
distro_packages:
    - base-devel
    - git
    - nodejs
    - python2-pip
    - ruby
    - openssh
    - nfs-utils
    - libevent
    - postgresql-libs
    - curl
    - tmux
    - vim
    - net-tools
    - vagrant
user_packages:
    google-chrome: ''
